services:
  backend:
    build:
      context: ./backend
      # platforms: [linux/amd64]  # uncomment for GKE deployment
    ports:
      - "50051:50051"

  envoy:
    build:
      context: ./envoy
      # platforms: [linux/amd64]  # uncomment for GKE deployment
    ports:
      - "8080:8080"
    depends_on:
      - backend

  frontend:
    build:
      context: ./frontend
      # platforms: [linux/amd64]  # uncomment for GKE deployment
    ports:
      - "8081:80"
    depends_on:
      - envoy
