package main

import (
	"context"
	"log"
	"net"

	pb "github.com/tempconv/backend/proto"
	"google.golang.org/grpc"
	"google.golang.org/grpc/reflection"
)

const port = ":50051"

// server implements the TemperatureConverterServer interface generated by protoc.
type server struct {
	pb.UnimplementedTemperatureConverterServer
}

func (s *server) CelsiusToFahrenheit(_ context.Context, req *pb.CelsiusRequest) (*pb.FahrenheitResponse, error) {
	f := req.GetCelsius()*9.0/5.0 + 32.0
	return &pb.FahrenheitResponse{Fahrenheit: f}, nil
}

func (s *server) FahrenheitToCelsius(_ context.Context, req *pb.FahrenheitRequest) (*pb.CelsiusResponse, error) {
	c := (req.GetFahrenheit() - 32.0) * 5.0 / 9.0
	return &pb.CelsiusResponse{Celsius: c}, nil
}

func main() {
	lis, err := net.Listen("tcp", port)
	if err != nil {
		log.Fatalf("failed to listen: %v", err)
	}

	grpcServer := grpc.NewServer()
	pb.RegisterTemperatureConverterServer(grpcServer, &server{})

	// reflection allows tools like grpcurl to discover services at runtime
	reflection.Register(grpcServer)

	log.Printf("gRPC server listening on %s", port)
	if err := grpcServer.Serve(lis); err != nil {
		log.Fatalf("failed to serve: %v", err)
	}
}
