// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: temperature.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CelsiusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Celsius       float64                `protobuf:"fixed64,1,opt,name=celsius,proto3" json:"celsius,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CelsiusRequest) Reset() {
	*x = CelsiusRequest{}
	mi := &file_temperature_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CelsiusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CelsiusRequest) ProtoMessage() {}

func (x *CelsiusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_temperature_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CelsiusRequest.ProtoReflect.Descriptor instead.
func (*CelsiusRequest) Descriptor() ([]byte, []int) {
	return file_temperature_proto_rawDescGZIP(), []int{0}
}

func (x *CelsiusRequest) GetCelsius() float64 {
	if x != nil {
		return x.Celsius
	}
	return 0
}

type FahrenheitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fahrenheit    float64                `protobuf:"fixed64,1,opt,name=fahrenheit,proto3" json:"fahrenheit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FahrenheitResponse) Reset() {
	*x = FahrenheitResponse{}
	mi := &file_temperature_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FahrenheitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FahrenheitResponse) ProtoMessage() {}

func (x *FahrenheitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_temperature_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FahrenheitResponse.ProtoReflect.Descriptor instead.
func (*FahrenheitResponse) Descriptor() ([]byte, []int) {
	return file_temperature_proto_rawDescGZIP(), []int{1}
}

func (x *FahrenheitResponse) GetFahrenheit() float64 {
	if x != nil {
		return x.Fahrenheit
	}
	return 0
}

type FahrenheitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fahrenheit    float64                `protobuf:"fixed64,1,opt,name=fahrenheit,proto3" json:"fahrenheit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FahrenheitRequest) Reset() {
	*x = FahrenheitRequest{}
	mi := &file_temperature_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FahrenheitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FahrenheitRequest) ProtoMessage() {}

func (x *FahrenheitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_temperature_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FahrenheitRequest.ProtoReflect.Descriptor instead.
func (*FahrenheitRequest) Descriptor() ([]byte, []int) {
	return file_temperature_proto_rawDescGZIP(), []int{2}
}

func (x *FahrenheitRequest) GetFahrenheit() float64 {
	if x != nil {
		return x.Fahrenheit
	}
	return 0
}

type CelsiusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Celsius       float64                `protobuf:"fixed64,1,opt,name=celsius,proto3" json:"celsius,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CelsiusResponse) Reset() {
	*x = CelsiusResponse{}
	mi := &file_temperature_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CelsiusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CelsiusResponse) ProtoMessage() {}

func (x *CelsiusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_temperature_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CelsiusResponse.ProtoReflect.Descriptor instead.
func (*CelsiusResponse) Descriptor() ([]byte, []int) {
	return file_temperature_proto_rawDescGZIP(), []int{3}
}

func (x *CelsiusResponse) GetCelsius() float64 {
	if x != nil {
		return x.Celsius
	}
	return 0
}

var File_temperature_proto protoreflect.FileDescriptor

const file_temperature_proto_rawDesc = "" +
	"\n" +
	"\x11temperature.proto\x12\vtemperature\"*\n" +
	"\x0eCelsiusRequest\x12\x18\n" +
	"\acelsius\x18\x01 \x01(\x01R\acelsius\"4\n" +
	"\x12FahrenheitResponse\x12\x1e\n" +
	"\n" +
	"fahrenheit\x18\x01 \x01(\x01R\n" +
	"fahrenheit\"3\n" +
	"\x11FahrenheitRequest\x12\x1e\n" +
	"\n" +
	"fahrenheit\x18\x01 \x01(\x01R\n" +
	"fahrenheit\"+\n" +
	"\x0fCelsiusResponse\x12\x18\n" +
	"\acelsius\x18\x01 \x01(\x01R\acelsius2\xc0\x01\n" +
	"\x14TemperatureConverter\x12S\n" +
	"\x13CelsiusToFahrenheit\x12\x1b.temperature.CelsiusRequest\x1a\x1f.temperature.FahrenheitResponse\x12S\n" +
	"\x13FahrenheitToCelsius\x12\x1e.temperature.FahrenheitRequest\x1a\x1c.temperature.CelsiusResponseB\x1bZ\x19github.com/tempconv/protob\x06proto3"

var (
	file_temperature_proto_rawDescOnce sync.Once
	file_temperature_proto_rawDescData []byte
)

func file_temperature_proto_rawDescGZIP() []byte {
	file_temperature_proto_rawDescOnce.Do(func() {
		file_temperature_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_temperature_proto_rawDesc), len(file_temperature_proto_rawDesc)))
	})
	return file_temperature_proto_rawDescData
}

var file_temperature_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_temperature_proto_goTypes = []any{
	(*CelsiusRequest)(nil),     // 0: temperature.CelsiusRequest
	(*FahrenheitResponse)(nil), // 1: temperature.FahrenheitResponse
	(*FahrenheitRequest)(nil),  // 2: temperature.FahrenheitRequest
	(*CelsiusResponse)(nil),    // 3: temperature.CelsiusResponse
}
var file_temperature_proto_depIdxs = []int32{
	0, // 0: temperature.TemperatureConverter.CelsiusToFahrenheit:input_type -> temperature.CelsiusRequest
	2, // 1: temperature.TemperatureConverter.FahrenheitToCelsius:input_type -> temperature.FahrenheitRequest
	1, // 2: temperature.TemperatureConverter.CelsiusToFahrenheit:output_type -> temperature.FahrenheitResponse
	3, // 3: temperature.TemperatureConverter.FahrenheitToCelsius:output_type -> temperature.CelsiusResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_temperature_proto_init() }
func file_temperature_proto_init() {
	if File_temperature_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_temperature_proto_rawDesc), len(file_temperature_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_temperature_proto_goTypes,
		DependencyIndexes: file_temperature_proto_depIdxs,
		MessageInfos:      file_temperature_proto_msgTypes,
	}.Build()
	File_temperature_proto = out.File
	file_temperature_proto_goTypes = nil
	file_temperature_proto_depIdxs = nil
}
